<?xml version="1.0"?>
<package format="3">
  <name>g1_joint_state_bridge</name>
  <version>0.0.1</version>
  <description>G1 LowState to JointState bridge</description>
  <maintainer email="user@todo.todo">user</maintainer>
  <license>Apache-2.0</license>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>unitree_go</depend>
  <depend>visualization_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>unitree_hg</depend>
  <buildtool_depend>ament_cmake</buildtool_depend>
</package>
